### ISSUE TITLE
Incorrect link in installation documentation.

### ISSUE THREAD

**Issue by spanjap** [jacobbates/pi-hole-midnight#12]
Following link is not working:
sudo wget https://raw.githubusercontent.com/MBarrows20/pi-hole-material-dark/install_Material_Dark_Theme.sh

Should be:
sudo wget https://raw.githubusercontent.com/MBarrows20/pi-hole-material-dark/master/install_Material_Dark_Theme.sh

With best regards,

**Comment by spanjap** [comment]
Wrong repo. Sorry

**Comment by M-Barrows** [comment]
> Wrong repo. Sorry

@spanjap no worries. I've gone ahead and updated the README in my fork. If the pull request is accepted, it will appear in this repo. Thanks for finding that mistake!
