### ISSUE TITLE
How to install this in piHole running on Docker?

### ISSUE THREAD

**Issue by mcnaveen** [jacobbates/pi-hole-midnight#13]

**Comment by pascaliske** [comment]
Hi @the-mcnaveen, I just installed it to my Docker-based Pi-hole setup. I just mounted the CSS file directly as a Docker volume in my `docker-compose.yml`:

```yaml
volumes:
  - ./path/to/pi-hole-midnight/skin-blue.min.css:/var/www/html/admin/style/vendor/skin-blue.min.css
```

I hope this helps you!

**Comment by mcnaveen** [comment]
Great :+1:
