### ISSUE TITLE
PiHole 5.0

### ISSUE THREAD

**Issue by phil-lipp** [jacobbates/pi-hole-midnight#14]
The graph (Total queries over last 24 hours & Client activity over last 24 hours) on the dashboard currently doesn't work with the beta release of PiHole. They are shown as bar diagram.

**Comment by phil-lipp** [comment]
Seems to be an intentional change from the main pihole design, my bad!

**Comment by M-Barrows** [comment]
> Seems to be an intentional change from the main pihole design, my bad!

@phil-lipp - Yes, you are correct that this visual change was intended. Bar Charts tend to be easier to interpret quickly and with more precision than pie charts.
