### ISSUE TITLE
piHole Versions show "N/A" in bottom of page

### ISSUE THREAD

**Issue by NoX1De** [jacobbates/pi-hole-midnight#2]
After installing this theme the pihole versions do not display and they all show up as "N/A"...

"Pi-hole Version N/A Web Interface Version N/A FTL Version N/A"

**Comment by jacobbates** [comment]
Hi NoX1De, I'm unable to recreate this issue at the moment. As it is only a CSS change to the style-blue.min.css file, I can't see how it can manipulate version text. What version of pi-hole are you running and do you have any other mod installed? You may need to update to the latest version before installing.

**Comment by jacobbates** [comment]
Unable to recreate issue user has reported. I believe what is described to be caused by something other than this simple css file modification.
