### ISSUE TITLE
Modification for Pi-hole V4.0

### ISSUE THREAD

**Issue by nokia3660** [jacobbates/pi-hole-midnight#5]
Text for "Reply" column in the query log needs to align with the color of the rest of the row.

![image](https://user-images.githubusercontent.com/36226959/43895062-74a9b732-9c17-11e8-8031-6a2a24ba5811.png)

**Comment by ail1020** [comment]
Looking at the html, this is because there is in-line styling happening. I'm no css guru, but I'm not sure this would be able to be fixed through css. @jacobbates might be able to give more insight though.

**Comment by jacobbates** [comment]
Hi @nokia3660 and @ail1020  - thanks for bringing this to my attention, I'll take a look when I'm home this evening and will see if I can resolve it.

**Comment by kyle95wm** [comment]
Any progress?

**Comment by jacobbates** [comment]
Hi guys, apols this is fixed now. Have forced the column to change color using:
`td:nth-child(6)`
If the Reply column is not your 6th column due to another modification, replace the number 6 in the CSS file with the correct column.
