### ISSUE TITLE
Latest Pi-Hole Update Seems to Have Broken Theme?

### ISSUE THREAD

**Issue by CytoStorm** [jacobbates/pi-hole-midnight#7]
As the title says, latest versions of Pi-Hole (Pi-hole Version v4.2.2 Web Interface Version v4.2 FTL Version v4.2.2) seems to have broken the theme? I've tried installing several times to no avail. Theme stays default. Love your theme by the way! Been using for a few years now.

**Comment by radiochild577** [comment]
Just installed for the first time on the latest version and it works perfectly for me. Did you make sure to clear your cookies so that the prior appearance gets flushed from memory?

Edit: working properly on desktop, but not on a Mobile/iPhone browser. 

Edit 2: it's now working on my iPhone.

**Comment by CytoStorm** [comment]
Seems to be a bit more finicky after Pi-Hole version changes now, but I'm up to date and have the theme working. Same issue as you, had to clear cache on my iPhone for it to apply on mobile. All good now, thanks for the tip!
